#include "TripleSys.h"
CC bool alldata::processOneDay()
{   // returns: false - go to prev day, true - day processed
	//if (iPlayer == 0)
	//	updateIndexPlayerMinMax();
	unsigned int cnt = 0;
	bool bCheckZCandidate = iDay >= 3 && m_useZStabilizer == 2;
	if (bCheckZCandidate)
 		return processZDay();
	while (iPlayer < m_numPlayers)
	{
		if (m_printMatrices && cnt++ > 300000000) {
#if !USE_CUDA
			printTableColor("Current row", tmpPlayers, 1, m_numPlayers, m_groupSize);
#endif
			cnt = 0;
		}
		if (iPlayer < 0)
			return false;
		const auto iPlayerNumber = getNextPlayer();

		if (iPlayerNumber >= m_numPlayers)
		{
			getPrevPlayer();
			continue;
		}
		else if (iPlayerNumber >= 0)
		{
			if (iPlayer + 1 < m_numPlayers)// && iPlayerNumber != indexPlayer[iPlayer])
				indexPlayer[iPlayer + 1] = m_indexPlayerMin[iPlayer + 1];
			tmpPlayers[iPlayer] = indexPlayer[iPlayer] = iPlayerNumber;
			selPlayers[iPlayerNumber] = iPlayer++; // check values of selPlayers only for equal or not to unset (-1)
		}
		else
		{
			iPlayer = m_numPlayers;
			break;
		}
		if (iPlayer == m_numPlayers && iDay > 0)
		{
			u1fSetTableRow(neighbors(iDay), tmpPlayers);
			if (m_use2RowsCanonization || param(t_u1f))
			{
				memcpy(result(iDay), tmpPlayers, m_numPlayers);
				//printTableColor("r2", result(1), 1, m_numPlayers, m_groupSize);
				m_playerIndex = m_numPlayers * (iDay + 1) - m_groupSize - 1;
				if (!checkNewRow(neighbors(), iDay + 1)) {
					while (iDay * m_numPlayers + iPlayer > m_playerIndex)
						getPrevPlayer();
					m_playerIndex = 0;
					continue;
				}
				m_playerIndex = 0;
			}
		}
	}
	return true;
}

CC bool alldata::processZDay()
{   // returns: false - go to prev day, true - day processed
	unsigned int cnt = 0;
	int iZStabilizerRow = completeGraph() ? m_indexPlayerMin[1] - 1 : m_indexPlayerMin[1] / 2;
	m_ZStabilizer->clearCurrent(iDay + 1);
	if (iPlayer == 0) {
		bool ret = m_ZStabilizer->generateCandidates(result(0), iZStabilizerRow);
		if (!ret)
			return false;
	}
	tchar* pRow;
	while (1)
	{
		if (iPlayer < 0) {
			printTable("[D] ip<0", result(), iDay + 1, m_numPlayers, m_groupSize);
			return false;
		}
		if (m_printMatrices && cnt++ > 300000000) {
#if !USE_CUDA
			printTableColor("Current z-row", tmpPlayers, 1, m_numPlayers, m_groupSize);
#endif
			cnt = 0;
		}
		if (!(pRow = m_ZStabilizer->getCandidate(iZStabilizerRow))) {
			iPlayer = -1;
			if (!linksFromMatrix(links(), result(), iDay, false, true)) {
				//continue;
				printTable("*** Internal error: duplicate links", result(), m_numDaysResult, m_numPlayers, m_groupSize);
				myExit(1);
			}
			//printf("-%d", tmpPlayers[1]);
			return false;
		}
		else {
			if (iPlayer >= m_numPlayers)
				iPlayer = m_numPlayers - m_groupSize - 1;
			if (iPlayer > 0 && memcmp(pRow, tmpPlayers, iPlayer) <= 0) {
				//if (tmpPlayers[1] > 10)
				//printf(".");
				continue;
			}
			iPlayer = m_numPlayers;
			memcpy(tmpPlayers, pRow, m_numPlayers);
			memcpy(result(iDay), tmpPlayers, m_numPlayers);
			if (!linksFromMatrix(links(), result(), iDay + 1, false, false)) {
				//printTable("[D] edge", result(), iDay + 1, m_numPlayers, m_groupSize);
				continue;
				printTable("*** Internal error: 1", result(), iDay + 1, m_numPlayers, m_groupSize);
				myExit(1);
			}
		}
#if 0
		static tchar r24[24] = 
		//{ 0,4,1,8,2,6,3,10,5,12,7,14,9,16,11,18,13,20,15,22,17,23,19,21 };
		{ 0,5,1,9,2,11,3,7,4,13,6,15,8,17,10,19,12,21,14,23,16,22,18,20 };
		tchar r22[22] = { 0,7,1,8,2,11,3,16,4,15,5,12,6,19,9,20,10,13,14,21,17,18 };
		int icmp = 2;
		if (iZStabilizerRow == 4) {
			//printTable("t", tmpPlayers, 1, m_numPlayers, 2);
			icmp = memcmp(r24, tmpPlayers, 4);
			//icmp = memcmp(nr, tmpPlayers, m_numPlayers - 8);
			if (icmp > 0) {
				getPrevPlayer(); 
				continue;
			}
			else {
				printTable("t", tmpPlayers, 1, m_numPlayers, 2);
				icmp = icmp;
			}
			if (iPlayer == m_numPlayers && icmp == 0)
				iDay = iDay;
		}
#endif
		u1fSetTableRow(neighbors(iDay), tmpPlayers);
		if (!m_use2RowsCanonization && !param(t_u1f))
			break;
		//printTableColor("r2", result(1), 1, m_numPlayers, m_groupSize);
		m_playerIndex = m_numPlayers * (iDay + 1) - m_groupSize - 1;
		if (!checkNewRow(neighbors(), iDay + 1)) {
			iPlayer = m_playerIndex - m_numPlayers * iDay + 1;
			m_playerIndex = 0;
			printfRed("*** Internal error: not P1F candidate generated by ZStabilizer\n");
			exit(1);
			continue;
		}
		m_playerIndex = 0;
		if (m_nPrecalcRows && iZStabilizerRow > 3)
			break;
		int index = iPlayer - m_groupSize - 1;
		int ic = m_ZStabilizer->check(tmpPlayers, result(iDay - 1), &index, iDay); // note: must be last check, or you need to cleanup aut.
		if (ic == 1) {
			//printf("+%d", tmpPlayers[1]);
			break;
		}
		m_ZStabilizer->clearCurrent(iDay + 1);
		//if (tmpPlayers[1] > 10)
		//printf("=");
		iPlayer = index + 1;
	}
	return true;
}
